


---

apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: ${APP_LABEL}
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  annotations:
    app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
    app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_LABEL}
  template:
    metadata:
      labels:
        app: ${APP_LABEL}
      annotations:
        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - env:
        - name: TZ
          value: America/Sao_Paulo
        - name: AMBIENTE
          value: ${AMBIENTE}
        name: ${APP_NAME}
        image: ${DOCKER_IMAGE_TAG}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "8Gi"
          requests:
            memory: 512Mi
        volumeMounts:
          - name:  ${APP_CONTEXT}-volume
            mountPath: "/data/datajud/etl"
      volumes:
        - name: ${APP_CONTEXT}-volume
          persistentVolumeClaim:
            claimName: pvc-datajud-batch
#      volumes:
#        - name:  ${APP_CONTEXT}-volume
#          flexVolume:
#            driver: "fstab/cifs"
#            fsType: "cifs"
#            secretRef:
#              name: "cifs-secret"
#            options:
#              networkPath: "//172.25.2.131/e"
#              mountOptions: "dir_mode=0755,file_mode=0755,noperm"

#        
      imagePullSecrets:
        - name: gitlab-auth
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${APP_NAME}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"

spec:
  rules:
    - host: ${DEPLOY_HOST}
      http:
        paths:
          - path: /
            backend:
              serviceName: ${APP_NAME}
              servicePort: 80

---
