version: '3.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: elastic-node1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx2g -Xms2g"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node
      network.host: 0.0.0.0
    networks:
      - elk

  datajud-logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.10.2
    ports:
      - "5044:5044"
      - "5000:5000"
      - "9600:9600"
    #command: bash -c "rm -f /usr/share/logstash/pipeline/logstash.conf || true"
    volumes:
     - type: bind
       source: ./config/pipelines.yml
       target: /usr/share/logstash/config/pipelines.yml
       read_only: true
     - type: bind
       source: /mnt/sda1/opt/java-8-oracle/jre/lib/security/cacerts
       target: /usr/share/logstash/config/cacerts.jks
       read_only: true
     - type: bind
       source: ./pipeline/
       target: /usr/share/logstash/pipeline/
       read_only: true
     - type: bind
       source: /mnt/sda1/DESENV/PROJETOS/DATAJUD/
       target: /tmp
       read_only: false
    environment:
      LS_JAVA_OPTS: "-Xmx2g -Xms2g"
    networks:
       elk:        
         #ipv4_address: 10.0.21.117


networks:
  elk:
    driver: bridge
    ipam:
      driver: default
      #config:
      #  - subnet: 10.0.21.0/24

volumes:
  esdata:
    driver: local
#volumes:
#  datalakeshare:
#    driver: local
#    driver_opts:
#      type: cifs
#      device: "//sddc-cjf-dtlk.cjf.local/e"
#      o: "credentials=user.cifs"
#      device: "//172.25.2.131/e"

      